quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=cafe_admin
quarkus.datasource.password=cafe123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cafe_db
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.jackson.write-dates-as-timestamps=false

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ecommerce-cafe
smallrye.jwt.sign.key.location=privateKey.pem